### ISSUE TITLE
Reminders Sort Fix

### ISSUE THREAD

**Issue by drakerienert** [mzeryck/Weather-Cal#55]
@mzeryck I think the Reminders code needs a slight tweak to correctly sort by date. I put my suggestion below. Correct me if I am wrong, I am very much a for fun amateur programmer, but this tweak worked for me. 

I switched the order of the sort and filter/slice functions (sort first and filter/slice second). Originally, the only reminders that were properly sorted by date were the first 3 (numberOfReminders) reminders in order of creation date. Everything else was left off even if it's due date came before. When I changed the value of numberOfRemindres = 12 (my total reminder list) the sort worked fine. When I made the change to the code order shown below, all of the reminders were properly sorted regardless of creation date. 

Example:  (numberOfReminders = 3)
Reminder 1 Due: tomorrow
Reminder 2 Due: in 7 days
Reminder 3 Due: in 2 days
Reminder 4 Due: Today
Reminder 5 Due: Yesterday (with overdue set to true)

Current code displays Reminders 1, 3, and 2.
New code displays Reminder 5, 4, 1. 

I hope that makes sense. 

```
`   // Sort in order of due date. SORT BEFORE THE FILTER/SLICE BELOW
    reminders.sort(function(a, b) {
    
      // Due dates are always picked first.
      if (!a.dueDate && b.dueDate) return 1
      if (a.dueDate && !b.dueDate) return -1
      if (!a.dueDate && !b.dueDate) return 0
    
      // Otherwise, earlier due dates go first.
      const aTime = a.dueDate.getTime()
      const bTime = b.dueDate.getTime()
      
      if (aTime > bTime) return 1
      if (aTime < bTime) return -1
      return 0 
    })
  
// Determine which reminders to show. DO THIS AFTER THE SORT. 
    let reminders = await Reminder.allIncomplete()
    reminders = reminders.filter(shouldShowReminder).slice(0,numberOfReminders)

    // Store the data.
    data.reminders.all = reminders
  }`

```
Thank you so much for this script, it is amazing. I also appreciate your work on the reminders part even though I think I read you don't use it.

**Comment by mzeryck** [comment]
@drakerienert Ah yes, you are totally right about that! I think what happened is that two different bug fixes ended up creating this third bug. Which, like you mentioned, I didn't notice since I don't use reminders! Whoops.

Your fix looks right to me - the only thing I noticed here, which might've just been due to copy/pasting into the comment, is that `let reminders = await Reminder.allIncomplete()` needs to happen before the sort. Otherwise this fix looks right to me.

Would you like to submit this code as a pull request? That way, GitHub automatically credits you for the change. 

And I'm glad you like Weather Cal! I'm definitely an amateur programmer too, I just really like Scriptable haha.

**Comment by drakerienert** [comment]
@mzeryck Good catch, I didn't mean to move the `let reminders` line. I submitted a pull request, hopefully I did it right. Thank you!
