### ISSUE TITLE
Configure default apps for items & reminders

### ISSUE THREAD

**Issue by aschilling** [mzeryck/Weather-Cal#61]
Hi Max,

thank you so much for sharing your code with us. It helped me a lot in customizing my homescreen. However, one thing I don't understand is how to touch targets (the app which open) for the events items are defined. Is it possible to open the events and reminders items not in the system defaults but with other apps e.g., Calendars from Readdle?

Best regards
Andreas

**Comment by mzeryck** [comment]
Hi Andreas, I'm glad you like Weather Cal! It's potentially possible to change those, although in many cases, there's no way to do it. For example, I haven't been able to make the reminders open in the Reminders app. For other apps, it's possible if they have a URL scheme. I can look into adding this!

**Comment by caslan34** [comment]
here it is. `reminderStack.url = "x-apple-reminderkit://REMCDReminder/`

**Comment by mzeryck** [comment]
@caslan34 I searched all over and couldn't find this - thank you! Would you be willing to submit a pull request with this added?

**Comment by caslan34** [comment]
@mzeryck firstly thank you for this widget.

I do not want to update now, because I added something.

I have two suggestions.
First, check attached picture. You will see, I added widget two reminders list. If you can, when we add two list in `selectList`, program must show both of lists. But also `numberOfReminders` Must be for two lists. 

Second, if you can find code about background of widget to be live and changeable with weather conditions. If it is rain, background will be rain, if it snow, background will be snow...

Thanks 
![3B2497A3-F3D2-4405-AC56-1132ABF9BD93](https://user-images.githubusercontent.com/65220005/99996797-8ac1f280-2dbc-11eb-9911-55634b713e2a.jpeg)

**Comment by TheRealEvan584** [comment]
I would also like to know if it is possible to change the background of the widget depending on if your phone is in light or dark mode.

**Comment by mzeryck** [comment]
@caslan34 Just so you know, if you run the "Update code" function from the settings menu, it will not reset your widget. So it's safe to do it! If you update, I added in customization for URL tap targets, and added your reminders URL (thank you!)
For your other two requests, I am not currently planning to implement them, although if you did you'd be welcome to submit a pull request.

@TheRealEvan584 I promise this is coming at some point!

**Comment by jianyu-li** [comment]
I wanted to just chime in here and let everyone know about a workaround for opening the iOS weather app when the weather items are tapped. I couldn’t find an X callback URL for this but there is one for the shortcuts app. If you create a shortcut called Weather that opens the weather app you can use this URL in preferences to trigger the shortcut. (Not perfect because it opens scriptable, shortcuts, and THEN weather. Still...it works. 

shortcuts://x-callback-url/run-shortcut?name=Weather

**Comment by jianyu-li** [comment]
> I wanted to just chime in here and let everyone know about a workaround for opening the iOS weather app when the weather items are tapped. I couldn’t find an X callback URL for this but there is one for the shortcuts app. If you create a shortcut called Weather that opens the weather app you can use this URL in preferences to trigger the shortcut. (Not perfect because it opens scriptable, shortcuts, and THEN weather. Still...it works.
> 
> shortcuts://x-callback-url/run-shortcut?name=Weather

I did hear that opening apps from shortcuts doesn’t require opening the shortcuts app in the newest iOS beta so there may be a silver lining

**Comment by mzeryck** [comment]
I'm going to close this issue since it was resolved. @jianyu-li I'm working on some better documentation, once it's a bit more ready I'd love to have you contribute this Shortcuts tip if you're interested. Stay tuned!

**Comment by djbeadle** [comment]
Note for anyone in the future looking for this, in iOS 15 the "URL to open when [current/hourly/daily] weather is tapped" can be set to `weather://` to open the built in weather app!

**Comment by jianyu-li** [comment]
> Note for anyone in the future looking for this, in iOS 15 the "URL to open when [current/hourly/daily] weather is tapped" can be set to `weather://` to open the built in weather app!

Nice
