### ISSUE TITLE
Celsius is not displayed even if metric is modified

### ISSUE THREAD

**Issue by hjm79** [mzeryck/Weather-Cal#77]
Celsius is not displayed even if metric is modified

Please help.

**Comment by mzeryck** [comment]
That's odd! Are you using Weather Cal from the Scriptable Gallery or directly downloaded from this GitHub project?

**Comment by starelee** [comment]
Although you've already closed this issues, Celsius isn't displayed again.
I set units as metric. But temperature looks like "283" something which is neither F nor C.
Tapping weather section, it goes to error page "weather.com" / {"error": "unsupported locale: ko-KO"}

it seems that this issue occurs to Korea, so I leave a comment.

**Comment by adamengineering** [comment]
The locale for Korea on the iPhone (current iOS) is: 'ko'
and not 'ko-KO'

**Comment by mzeryck** [comment]
@hjm79 @starelee @adamengineering I believe there is a fix now. Please run the "Update code" function. After that, go to "Edit preferences", then "Weather". You can now select a locale code directly - for example, "kr" for Korea. This will only apply to the weather data, since the OpenWeather service is more restrictive. (It may take a couple minutes to work.)

Please let me know if that fixes the issue!

**Comment by starelee** [comment]
It works! Thanks a lot!
