### ISSUE TITLE
Automatic background change with respect to sunset 

### ISSUE THREAD

**Issue by baby-bird** [mzeryck/Weather-Cal#81]
What could be done in 
`custom`
section to get automatic background change with respect to sunset?
The passed `widget` variable contains no sunset data so there are limited code available without changing original code.

**Comment by mzeryck** [comment]
Because `custom` is declared after `weather-cal-code` is imported into the `code` object, you have access to all of the Weather Cal backend. So if you want to use sunrise/sunset data, make sure this is at the top of your code:
```javascript
if (!code.data.sun) { await code.setupSunrise() }
```
Then, you can access the sunrise data. It's stored in milliseconds:
```javascript
code.data.sun.sunrise
code.data.sun.sunset
code.data.sun.tomorrow
```
I know this isn't documented yet, but I want to do that soon!
