### ISSUE TITLE
Hello can you help with this please

### ISSUE THREAD

**Issue by ianlee511** [mzeryck/Weather-Cal#83]
![358B4767-64C7-4219-B89A-FCC7F4DC86B1](https://user-images.githubusercontent.com/64882476/100880397-06741b80-34f0-11eb-8a5d-6e0164a4e402.png)
Can you help?

**Comment by mzeryck** [comment]
Can you try deleting the "Weather Cal code" script, and then running this "Weather" script again, to see if that helps?

**Comment by ianlee511** [comment]
When I run weather than it makes the weather cal script and the same error occurs

**Comment by mzeryck** [comment]
Hm, that's odd. Can you show me what your layout looks like?

**Comment by ianlee511** [comment]
I’m not sure what the layout is if I just run the script after i did the first setup it would keep saying the error on the picture above

**Comment by mzeryck** [comment]
If you're still experiencing this issue, can you copy the code from the "Weather" and "Weather Cal code" scripts into http://pastebin.com so I can take a look?

**Comment by ianlee511** [comment]
https://pastebin.com/mvz3FKb4 Weather
https://pastebin.com/B06rn1g6 Weather cal

**Comment by mzeryck** [comment]
@ianlee511 This is a very perplexing bug - the two scripts you shared work fine on my device. Can you tell me which version of Scriptable you have? (In the app, tap the gear icon, then About.)

**Comment by icsAT** [comment]
@ianlee511 and @mzeryck I also tried the code provided by @ianlee511 on my device and it worked fine. 

@mzeryck my thoughts on this:
- the error is raised on the first line of the function "row(input, parameter)"
- "this.widget" is not defined
- btw. "input" is declared in the function and never read, and "parameter" is never passed
- the function "row" is only called from the function "processASCIILine(lineInput)" if there is a line that starts and ends with dashes
- the function "processASCIILine" is only called from function "processLine(lineInput,wc)" if there is a line that starts and ends with dashes
- btw. "wc" is declared in the function and never read
- on the provided layout I do not find anything that looks like any dash to me
- in the conclusion i found nothing that should lead into the function that raises the error in the screenshot, which is very strange to me

@ianlee511:
Since your provided code is a little bit outdated by now and Max did some changes I think it would be good if you try again with the actual code. I would recomend, that you delete all the weather cal scripts from Scriptable and set up a new  script with [this code](https://github.com/mzeryck/Weather-Cal/blob/main/weather-cal.js). Check if this runs out of the box with no error. If this raises an error please post it again.
And also check the version of Scriptable as Max suggested and check if there are any updates for Scriptable.

Greetings André

**Comment by ianlee511** [comment]
![850C42AE-E52A-4174-A668-693BF9F7AACA](https://user-images.githubusercontent.com/64882476/102770251-28faa580-43c7-11eb-985c-c63771c9df18.png)
Is there anything I need to touch about the stack?

**Comment by icsAT** [comment]
@ianlee511 the error still comes up at the same line of code as before and i still do not understand why this function got called in first place. In my opinion it should not. Hopefully Max has an idea, bacause i don't.

Maybe you could help figuring something out. Are you able to add a line in the code?
Line 525 should be empty. Could you add a "console.log(line)"

Before:
`  // Processes a single line of ASCII. 
  async processASCIILine(line) {

    // If it's a line, enumerate previous columns (if any) and set up the new row.
    if (line[0] == "-" && line[line.length-1] == "-") {`

After:
`  // Processes a single line of ASCII. 
  async processASCIILine(line) {
console.log(line)
    // If it's a line, enumerate previous columns (if any) and set up the new row.
    if (line[0] == "-" && line[line.length-1] == "-") {`

Then run the script from Scriptable and post the log-output like you did on the first screenshot?

**Comment by mzeryck** [comment]
Closing this due to lack of response, although please do reopen if you end up running the test suggested above.
