### ISSUE TITLE
Error on line XXX:YY: TypeError: this.currentRow.addStack/column.addStack is not a function

### ISSUE THREAD

**Issue by icsAT** [mzeryck/Weather-Cal#92]
Hi,

I just updated the code of your script by using the update function and now it throws an error.

My medium widget ([Code here](https://gist.github.com/icsAT/1b832fa894fbe3fc1df99272c6ffd567)) says:
"Error on line 586:50: TypeError: this.currentRow.addStack is not a function. (In 'this.currentRow.addStack()', 'this.currentRow.addStack' is undefined)"
This seems to be in the column function

My big widget ([Layout also here](https://gist.github.com/icsAT/1b832fa894fbe3fc1df99272c6ffd567)) says:
"Error on line 601:43: TypeError: column.addStack is not a function. (In 'column.addStack()', 'column.addStack' is undefined)"
This seems to be in the align function

While searching for some more informations on this issue I found out, what the problem was:
I still defined the items with a trailing comma. This seems not to be supportet any more. After removing them it is working again.

So not that much an issue to me any more, but maybe a hint if someone else is running into this problem.

Greetings from Germany,

André

**Comment by mzeryck** [comment]
Hi André, thanks so much for pointing this out! When I was rewriting the layout code, I totally forgot that some folks still have trailing commas. I reintroduced this in the latest commit. (I also allow for trailing periods - because when you're building an ASCII layout, iOS adds a period if you add two spaces in a row.)
