### ISSUE TITLE
Error when adding “news”

### ISSUE THREAD

**Issue by LTLNEMO** [mzeryck/Weather-Cal#95]
Added "news" in layout view and got this

Error on line 1671:39: Expected value of type string but got value of type undefined.

**Comment by icsAT** [comment]
@LTLNEMO,

I could confirm this issue. If you chage the basic stetting for "Display the publishe date for each news item" from "none" to any thing else it will work.

@mzeryck.
in the news function you set dateText by switching "newsSettings.showDate". Unfortunately there is no case for the default setting "none" of showDate. "dateText" is then undefined and the function provideText throws an error.

Greetings Andre

**Comment by LTLNEMO** [comment]
Changed to relative and got 

Error on line 1506:32: Expected value of type Date but got value of type string.

**Comment by mzeryck** [comment]
@icsAT Thank you for figuring this out! I am a bit busy this morning, so please feel free to submit a pull request with a fix if you like, otherwise I will be happy to look into this in a few hours.

**Comment by icsAT** [comment]
@LTLNEMO you are right with the second problem too.

@mzeryck the problem is, that the cached date (news.item.date) has not a date format. It is a string. So there is a problem, because the formatDate function needs a date and not a string. If it is read from cnn everything ist fine by the way.

I will try to submit a pull request with a quick fix. Never done it before, so we will see ;-)
